# - hosts: openstack
#   become: true
#   roles:
#     - role: common
#       tags: [ setup, shared ]
   
- hosts: computes
  become: true
  roles:
    - role: compute
      tags: [ compute ]
