- hosts: openstack
  become: true
  roles:
    - role: common
      tags: [ common, setup, shared ]
   
- hosts: controllers
  become: true
  roles:
    - role: controller
      tags: [controller]

- hosts: computes
  become: true
  strategy: free
  roles:
    - role: compute
      tags: [ compute ]


### DO NOT UNCOMMENT UNTIL PRODUCTION IS READY ###
- hosts: blocks
  become: true
  roles:
    - role: block
      tags: [ block ]