---
- name: 'display warning'
  pause:
    prompt: "This host should have two more partitions labelled: /dev/sdb /dev/sdc, if this hasn't been done please abort this playbook. View https://docs.openstack.org/cinder/train/install/cinder-storage-install-rdo.html for more information."

- name: 'install packages'
  yum:
    name:
      - centos-release-openstack-train
    state: present
  tags:
    - basic
    
- name: 'Upgrade all packages'
  yum:
    name: '*'
    state: latest
  tags:
    - basic

- name: 'copy chrony template'
  template:
    backup: yes
    src: chrony.conf.j2
    dest: /etc/chrony.conf
  register: chrony_update
  tags:
    - basic

- name: 'restart chrony'
  systemd:
    name: chronyd
    state: restarted
    enabled: yes
  when: chrony_update is changed
  tags:
    - basic

- name: 'install cinder packages'
  yum:
    name:
      - lvm2
      - device-mapper-persistent-data
      - openstack-cinder
      - targetcli
      - python-keystone
    state: present
  register: install_cinder

- name: 'setup cinder'
  block:
    - name: 'enable lvm'
      systemd:
        name: lvm2-lvmetad.service
        state: started
        enabled: yes
    - name: 'create volume'
      shell:  |
        pvcreate {{item}}
        vgcreate cinder-volumes {{item}}
      loop:
        - /dev/sdb
    - name: 'copy lvm conf'
      template:
        src:  cinder/lvm.conf.j2
        dest: /etc/lvm/lvm.conf 
        backup: yes
    - name: 'copy conf'
      template:
        src:  cinder/cinder.conf.j2
        dest: /etc/cinder/cinder.conf 
        backup: yes
    - name: 'update permissions'
      shell: chown -R glance:glance /var/log/glance/api.log
    - name: 'disable selinux'
      shell: setenforce 0
    - name: 'start cinder volumes'
      systemd:
        name: openstack-cinder-volume.service
        state: started
        enabled: yes
        # ( ͡° ͜ʖ ͡°)
    - name: 'gimmie dat service'
      systemd:
        name:  target.service
        state: started
        enabled: yes
  when: install_cinder is changed