---
- name: 'display warning'
  pause:
    prompt: "This host should have two more partitions labelled: /dev/sdb /dev/sdc, if this hasn't been done please abort this playbook. View https://docs.openstack.org/cinder/train/install/cinder-storage-install-rdo.html for more information."

- name: 'install cinder packages'
  yum:
    name:
      - lvm2 
      - device-mapper-persistent-data
      - openstack-cinder 
      - targetcli
      - python-keystone
    state: present
  register: install_cinder

- name: 'setup cinder'
  block:
    - name: 'enable lvm'
      systemd:
        name: lvm2-lvmetad.service
        state: started
        enabled: yes
    - name: 'create volume'
      shell:  |
        pvcreate /dev/sdb
        vgcreate cinder-volumes /dev/sdb
    - name: 'copy lvm conf'
      template:
        src:  cinder/lvm.conf.j2
        dest: /etc/lvm/lvm.conf 
        backup: yes
    - name: 'copy conf'
      template:
        src:  cinder/cinder.conf.j2
        dest: /etc/cinder/cinder.conf 
        backup: yes
    - name: 'start cinder volumes'
      systemd:
        name: openstack-cinder-volume.service
        state: started
        enabled: yes
    - name: 'start target service'
      systemd:
        name:  target.service
        state: started
        enabled: yes
        # ( ͡° ͜ʖ ͡°)
  when: install_cinder is changed
