---
- hosts: blocks
  tasks:
  
    - name: 'display warning'
      pause:
        prompt: "Make sure you have fully wiped the drives or else 'make cluster' does not work!"
    - name: 'teardown cinder'
      yum:
        name:
          - lvm2
          - device-mapper-persistent-data
          - openstack-cinder
          - targetcli
          - python-keystone
        state: removed
      tags:
        - block
    - name: 'Clean Volume'
      shell: "wipefs -a /dev/sdb"
      tags:
        - block