---
- name: Hostfile generation
  hosts: all
  become: true
  tasks:
    - name: Gather missing facts from ALL hosts
      setup:
        delegate_to: "{{ item }}"
        delegate_facts: True
      when: hostvars[item]['ansible_default_ipv4'] is not defined
      with_items: "{{ groups['all'] }}"
