---
- hosts: computes
  order: inventory
  tasks:
    - name: test connection
      systemd:
        name:
          - openstack-nova-compute.service
          - neutron-linuxbridge-agent.service
        state: stopped
