---
- name: 'update and upgrade packages'
  yum:
    update_cache: 'yes'
    name: '*'
    state: latest
  register: updated_packages
  tags:
    - common
    - basic
    - upgrade

- name: 'set host'
  hostname:
    name: "{{ inventory_hostname }}"
  when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')
  register: hostname
  tags:
    - common
    - basic
    - hosts
    
- name: 'update hosts'
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ hostvars[item]['ansible_host'] }}.+$"
    line: "{{ hostvars[item]['ansible_host'] }} {{ item }} {{ item }}.usdcyber.edu"
    state: present
    backup: yes
  with_items: "{{ groups['all'] }}"
  tags:
    - common
    - basic
    - hosts

- name: 'set timezone'
  timezone:
    name: "{{openstack_timezone}}"
  register: timezone
  tags:
    - common
    - basic
    - timezone

- name: 'check dependencies'
  yum:
    name: ['python', 'python3', 'make']
    state: present
  tags:
    - common
    - basic
    - packages
    
- name: Reboot system
  shell: sleep 1s && reboot
  async: 1
  poll: 0
  ignore_errors: true
  when: "(updated_packages is changed) or (timezone is changed) or (hostname is changed)"
  tags:
    - common
    - basic
    - reboot

- name: Wait for reboot
  local_action: wait_for host={{ ansible_host }} port=22 state=started delay=10
  become: false
  when: "(updated_packages is changed) or (timezone is changed) or (hostname is changed)"
  tags:
    - common
    - basic
    - reboot